"""
SymPy equivalents for Wolfram Language snippets from proposition_logic.tex / proposition_logic.html.
Auto-generated by /wolfram-to-sympy skill.
"""

from sympy import symbols, And, Or, Not, Implies, Equivalent, simplify, true, false
from sympy.logic.boolalg import truth_table, to_cnf, to_dnf, Xor
from sympy.logic.inference import satisfiable

# ── Variables ──────────────────────────────────────────────────────────
p, q, r = symbols('p q r')


# ══════════════════════════════════════════════════════════════════════
# Slide 3 — Proposition
# ══════════════════════════════════════════════════════════════════════

# Wolfram: In[1]:= {Boole[True], Boole[False]}
# Wolfram: Out[1]= {1, 0}
result = [int(True), int(False)]
assert result == [1, 0]          # → Out: {1, 0}


# ══════════════════════════════════════════════════════════════════════
# Slide 4 — Basic Operators: Negation
# ══════════════════════════════════════════════════════════════════════

# Wolfram: {¬p, !p, Not[p]}
neg_p = ~p          # same as Not(p)
assert Not(p) == neg_p

# Negation truth table
# Wolfram: TruthTable[Not[p], {p}]
print("NOT truth table:")
for row in truth_table(~p, [p]):
    print(f"  p={row[0][0]}  →  ¬p={row[1]}")


# ══════════════════════════════════════════════════════════════════════
# Slide 4 — Basic Operators: Conjunction
# ══════════════════════════════════════════════════════════════════════

# Wolfram: {p∧q, p&&q, And[p,q]}
conj = p & q        # same as And(p, q)
assert And(p, q) == conj


# ══════════════════════════════════════════════════════════════════════
# Slide 5 — Basic Operators: Disjunction
# ══════════════════════════════════════════════════════════════════════

# Wolfram: {p∨q, p||q, Or[p,q]}
disj = p | q        # same as Or(p, q)
assert Or(p, q) == disj

# Disjunction truth table
# Wolfram: TruthTable[Or[p,q], {p,q}]
print("\nOR truth table:")
for row in truth_table(p | q, [p, q]):
    vals, out = row
    print(f"  p={vals[0]}  q={vals[1]}  →  p∨q={out}")


# ══════════════════════════════════════════════════════════════════════
# Slide 6 — Example (exam propositions)
# p = "I studied for the exam"
# q = "I passed the exam"
# ══════════════════════════════════════════════════════════════════════

# Wolfram: ¬q           → "I did not pass the exam."
not_q = ~q

# Wolfram: p∧q          → "I studied for the exam and I passed the exam."
p_and_q = p & q

# Wolfram: ¬q∧¬p        → "I did not pass the exam, nor did I study for it."
not_q_and_not_p = ~q & ~p

# Wolfram: p∧¬q         → "I studied for the exam, but I did not pass it."
p_and_not_q = p & ~q


# ══════════════════════════════════════════════════════════════════════
# Slide 7 — More Operators: Conditional
# ══════════════════════════════════════════════════════════════════════

# Wolfram: {p⇒q, Implies[p,q]}
cond = Implies(p, q)

# Conditional truth table
# Wolfram: TruthTable[Implies[p,q], {p,q}]
print("\nIMPLIES truth table:")
for row in truth_table(Implies(p, q), [p, q]):
    vals, out = row
    print(f"  p={vals[0]}  q={vals[1]}  →  p⇒q={out}")


# ══════════════════════════════════════════════════════════════════════
# Slide 7 — More Operators: Biconditional
# ══════════════════════════════════════════════════════════════════════

# Wolfram: {p⟺q, Equivalent[p,q]}
bicond = Equivalent(p, q)

# Biconditional truth table
print("\nEQUIVALENT (↔) truth table:")
for row in truth_table(Equivalent(p, q), [p, q]):
    vals, out = row
    print(f"  p={vals[0]}  q={vals[1]}  →  p⟺q={out}")


# ══════════════════════════════════════════════════════════════════════
# Slide 8 — Example (rain/Kala propositions)
# p = "It is raining"
# q = "Kala wants to play outside"
# ══════════════════════════════════════════════════════════════════════

# Wolfram: p⇒q          → "If it is raining, then Kala wants to play outside."
rain_implies_play = Implies(p, q)

# Wolfram: ¬q⟺p        → "Kala does not want to play outside iff it is raining."
not_q_iff_p = Equivalent(~q, p)

# Wolfram: q∨p          → "Either Kala wants to play outside or it is raining."
q_or_p = q | p

# Wolfram: (p⇒q)∧(¬p⇒q) → "Kala wants to play outside if it is raining and if not."
always_play = Implies(p, q) & Implies(~p, q)
# Simplifies to just q
simplified = simplify(always_play)
print(f"\n(p⇒q)∧(¬p⇒q) simplifies to: {simplified}")  # → q


# ══════════════════════════════════════════════════════════════════════
# Slide 10 — Precedence examples
# Wolfram: {p,q} = {True, False}
# ══════════════════════════════════════════════════════════════════════

# Wolfram: In[2]:= {p, q} = {True, False}
# Wolfram: Out[2]= {True, False}
p_val, q_val = True, False

# Wolfram: In[3]:= ¬p∨q⇒p∧¬q  evaluates to True
# Precedence: () > ¬ > ∧ > ∨ > ⇒ > ⟺
# Parsed as: (¬p ∨ q) ⇒ (p ∧ ¬q)
expr1 = Implies(~p | q, p & ~q)
val1 = expr1.subs({p: p_val, q: q_val})
assert val1 == True, f"Expected True, got {val1}"   # → Out: True
print(f"\n¬p∨q⇒p∧¬q  with p=T,q=F  →  {val1}")

# Wolfram: ¬p∨q∨(p∧q∨True) ⇒ p∧q
# Parsed as: (¬p ∨ q ∨ (p∧q) ∨ True) ⇒ (p∧q)
expr2 = Implies(~p | q | (p & q) | True, p & q)
val2 = expr2.subs({p: p_val, q: q_val})
print(f"¬p∨q∨(p∧q∨True)⇒p∧q  with p=T,q=F  →  {val2}")


# ══════════════════════════════════════════════════════════════════════
# Slide 11 — Converse, Contrapositive, Inverse, Opposite
# Consider p⇒q
# ══════════════════════════════════════════════════════════════════════

# Wolfram: converse        q⇒p
converse       = Implies(q, p)

# Wolfram: contrapositive  ¬q⇒¬p
contrapositive = Implies(~q, ~p)

# Wolfram: inverse         ¬p⇒¬q
inverse        = Implies(~p, ~q)

# Wolfram: opposite        ¬(p⇒q)
opposite       = ~Implies(p, q)

# The contrapositive is logically equivalent to the original conditional
original = Implies(p, q)
# NOTE: Equivalent() on formulas checks symbolic equivalence
print(f"\np⇒q  ≡  ¬q⇒¬p  →  {Equivalent(original, contrapositive)}")  # True
print(f"p⇒q  ≡  q⇒p     →  {Equivalent(original, converse)}")          # Not always
